services:

  mysql:
    image: mariadb:10.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nconf
      MYSQL_USER: nconf
      MYSQL_PASSWORD: nconfpass
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - monitoring

  naemon:
    build: ./naemon
    container_name: naemon
    depends_on:
      - mysql
    volumes:
      - ./naemon/etc/naemon:/etc/naemon
      - ./naemon/var:/var/log/naemon
      - ./naemon/spool/checkresults:/usr/local/var/spool/checkresults
      - ./naemon/pnp4nagios/var:/usr/local/pnp4nagios/var
    networks:
      - monitoring

  thruk:
    build: ./thruk
    container_name: thruk
    depends_on:
      - naemon
    ports:
      - "8080:80"
    volumes:
      - naemon-live:/var/lib/naemon
    networks:
      - monitoring

  gearmand:
    image: artefactual/gearmand:latest
    container_name: gearmand
    ports:
      - "4730:4730"
    networks:
      - monitoring

  worker1:
    build: ./worker
    container_name: worker1
    depends_on:
      - gearmand
    volumes:
      - ./worker/worker.conf:/usr/local/etc/mod_gearman/worker.conf:ro
    networks:
      - monitoring
    entrypoint: ["tail", "-f", "/dev/null"]
    command: []

  worker2:
    build: ./worker
    container_name: worker2
    depends_on:
      - gearmand
    volumes:
      - ./worker/worker.conf:/usr/local/etc/mod_gearman/worker.conf:ro
    networks:
      - monitoring
    entrypoint: ["tail", "-f", "/dev/null"]
    command: []

  worker3:
    build: ./worker
    container_name: worker3
    depends_on:
      - gearmand
    volumes:
      - ./worker/worker.conf:/usr/local/etc/mod_gearman/worker.conf:ro
    networks:
      - monitoring
    entrypoint: ["tail", "-f", "/dev/null"]
    command: []

  pnp4nagios:
    build: ./pnp4nagios
    container_name: pnp4nagios
    depends_on:
      - naemon
      - mysql
    networks:
      - monitoring

  nconf:
    build: ./nconf
    container_name: nconf
    ports:
      - "8888:80"
    depends_on:
      - mysql
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  naemon-live:
